version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phone_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phone_numbers
      - ADMIN_PASSWORD=changeme
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phone_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - ADMIN_PASSWORD=changeme
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: phone_db
    restart: always
    environment:
      POSTGRES_DB: phone_numbers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phone_numbers"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
